/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.DongGopPanelController;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import views.Payment.AddEvent;
import views.Payment.DanhSachChuaDong;
import views.Payment.ListEvent;
import views.Payment.ListPayment;

/**
 *
 * @author Administrator
 */
public class DongGopPanel extends javax.swing.JPanel {

    private JFrame parentFrame;
    private int eventID;
    private DongGopPanelController dongGopController;

    public DongGopPanel(JFrame parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        this.dongGopController = new DongGopPanelController(JpnTable);
        dongGopController.setParentJFrame(parentFrame);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEventBtn = new javax.swing.JButton();
        ListBtn = new javax.swing.JButton();
        JpnTable = new javax.swing.JPanel();
        JbtChuaDong = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        AddEventBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddEventBtn.setText("Thêm sự kiện");
        AddEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventBtnActionPerformed(evt);
            }
        });

        ListBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListBtn.setText("Danh sách đóng");
        ListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnTableLayout = new javax.swing.GroupLayout(JpnTable);
        JpnTable.setLayout(JpnTableLayout);
        JpnTableLayout.setHorizontalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        JpnTableLayout.setVerticalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JbtChuaDong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JbtChuaDong.setText("Danh sách chưa đóng");
        JbtChuaDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtChuaDongActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Quản lý sự kiện");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEventBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JbtChuaDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(AddEventBtn)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(109, 109, 109)
                .addComponent(ListBtn)
                .addGap(28, 28, 28)
                .addComponent(JbtChuaDong)
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(JpnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventBtnActionPerformed
        AddEvent addEvent = new AddEvent();
        addEvent.setLocationRelativeTo(null);
        addEvent.setResizable(false);
        addEvent.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addEvent.setVisible(true);

    }//GEN-LAST:event_AddEventBtnActionPerformed

    private void ListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListBtnActionPerformed
        ListPayment listPaymentView = new ListPayment();
        listPaymentView.setLocationRelativeTo(null);
        listPaymentView.setMinimumSize(new Dimension(1000, 600));
        listPaymentView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        listPaymentView.setVisible(true);
    }//GEN-LAST:event_ListBtnActionPerformed

    private void JbtChuaDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtChuaDongActionPerformed
        // TODO add your handling code here:
        DanhSachChuaDong dsChuaDong = new DanhSachChuaDong();
        dsChuaDong.setLocationRelativeTo(null);
        dsChuaDong.setMinimumSize(new Dimension(1000, 600));
        dsChuaDong.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dsChuaDong.setVisible(true);
    }//GEN-LAST:event_JbtChuaDongActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListEvent listEvent = new ListEvent();
        listEvent.setLocationRelativeTo(null);
        listEvent.setMinimumSize(new Dimension(1000, 600));
        listEvent.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        listEvent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventBtn;
    private javax.swing.JButton JbtChuaDong;
    private javax.swing.JPanel JpnTable;
    private javax.swing.JButton ListBtn;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
