/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.DongGopPanelController;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import views.Payment.AddEvent;
import views.Payment.ListPayment;

/**
 *
 * @author Administrator
 */
public class DongGopPanel extends javax.swing.JPanel {

    private JFrame parentFrame;
    private int eventID;
    private DongGopPanelController dongGopController;

    public DongGopPanel(JFrame parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        this.dongGopController = new DongGopPanelController(JpnTable);
        dongGopController.setParentJFrame(parentFrame); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEventBtn = new javax.swing.JButton();
        ListBtn = new javax.swing.JButton();
        JpnTable = new javax.swing.JPanel();

        AddEventBtn.setText("Thêm Event");
        AddEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventBtnActionPerformed(evt);
            }
        });

        ListBtn.setText("Danh sách");
        ListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnTableLayout = new javax.swing.GroupLayout(JpnTable);
        JpnTable.setLayout(JpnTableLayout);
        JpnTableLayout.setHorizontalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        JpnTableLayout.setVerticalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEventBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(AddEventBtn)
                .addGap(67, 67, 67)
                .addComponent(ListBtn)
                .addContainerGap(187, Short.MAX_VALUE))
            .addComponent(JpnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventBtnActionPerformed
        AddEvent addEvent = new AddEvent();
        addEvent.setLocationRelativeTo(null);
        addEvent.setResizable(false);
        addEvent.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addEvent.setVisible(true);

    }//GEN-LAST:event_AddEventBtnActionPerformed

    private void ListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListBtnActionPerformed
        ListPayment listPaymentView = new ListPayment();
        listPaymentView.setLocationRelativeTo(null);
        listPaymentView.setMinimumSize(new Dimension(1000,600));
        listPaymentView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        listPaymentView.setVisible(true);
    }//GEN-LAST:event_ListBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventBtn;
    private javax.swing.JPanel JpnTable;
    private javax.swing.JButton ListBtn;
    // End of variables declaration//GEN-END:variables
}
