/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Payment;

import javax.swing.JOptionPane;
import services.DongGopService;

/**
 *
 * @author Administrator
 */
public class ChangePayment extends javax.swing.JFrame {

    /**
     * Creates new form ChangePayment
     */
    private int paymentID;
    private final DongGopService donggopService = new DongGopService();
    public ChangePayment(int paymentID, int eventID, String idHoKhau, String tenChuho, int sotien, String ghichu) {
        initComponents();
        this.paymentID = paymentID;
        JlbSukien.setText(String.valueOf(eventID));
        JlbTenchuho.setText(tenChuho);
        JlbHoKhau.setText(idHoKhau);
        JtfSotien.setText(String.valueOf(sotien));
        JtfGhichu.setText(ghichu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtfGhichu = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        JtfSotien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JlbSukien = new javax.swing.JLabel();
        JlbHoKhau = new javax.swing.JLabel();
        JlbTenchuho = new javax.swing.JLabel();
        JbtOk = new javax.swing.JButton();
        JbtDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Sự kiện");

        jLabel2.setText("ID hộ Khẩu");

        jLabel3.setText("Tên Chủ hộ");

        jLabel4.setText("Số tiền đóng");

        JtfGhichu.setColumns(20);
        JtfGhichu.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        JtfGhichu.setRows(5);
        jScrollPane1.setViewportView(JtfGhichu);

        jLabel5.setText("Ghi chú");

        jLabel6.setText("x1000 đồng");

        JlbSukien.setText("jLabel7");

        JlbHoKhau.setText("jLabel7");

        JlbTenchuho.setText("jLabel7");

        JbtOk.setText("Lưu thay đổi");
        JbtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtOkActionPerformed(evt);
            }
        });

        JbtDel.setText("Xóa đóng góp");
        JbtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JtfSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(JlbSukien)
                                    .addComponent(JlbHoKhau)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(JbtOk))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JlbTenchuho)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(JbtDel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JlbSukien))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(JlbHoKhau)
                    .addComponent(JlbTenchuho))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JtfSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JbtDel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(JbtOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtOkActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thay đổi??", "Cảnh báo", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            String tmp = JtfSotien.getText();
            int value;
            try {
                value = Integer.parseInt(tmp);
            } catch (Exception e) {
                dispose();
                value = 0;
            }
            String ghichu = JtfGhichu.getText();
            boolean b =donggopService.updatePayment(paymentID, value, ghichu);
            if(b) {
                JOptionPane.showMessageDialog(null, "OK!! ", "Đã lưu thay đổi!!", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra!! ", "Warning!!", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_JbtOkActionPerformed

    private void JbtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtDelActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa??", "Cảnh báo", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            boolean b =donggopService.delPayment(paymentID);
            if(b) {
                JOptionPane.showMessageDialog(null, "OK!! ", "Đã Xóa!!", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra!! ", "Warning!!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_JbtDelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtDel;
    private javax.swing.JButton JbtOk;
    private javax.swing.JLabel JlbHoKhau;
    private javax.swing.JLabel JlbSukien;
    private javax.swing.JLabel JlbTenchuho;
    private javax.swing.JTextArea JtfGhichu;
    private javax.swing.JTextField JtfSotien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
