/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Payment;

import controllers.DanhSachDongGopController;
import controllers.DongGopPanelController;
import javax.swing.JComboBox;

/**
 *
 * @author Administrator
 */
public class DanhSachChuaDong extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachChuaDong
     */
    private DongGopPanelController dongGopController;

    public DanhSachChuaDong() {
        initComponents();
        this.setTitle("Danh sách chưa đóng góp ");
        dongGopController = new DongGopPanelController();
        dongGopController.setDataToComboBox(JcbEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JcbEvent = new javax.swing.JComboBox<>();
        JpnTable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JcbEvent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JcbEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JcbEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnTableLayout = new javax.swing.GroupLayout(JpnTable);
        JpnTable.setLayout(JpnTableLayout);
        JpnTableLayout.setHorizontalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JpnTableLayout.setVerticalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JcbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JcbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbEventActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String eventName = (String)cb.getSelectedItem();
        if(eventName.indexOf(':') <0 ) return;
        int eventID = Integer.parseInt(eventName.substring(0, eventName.indexOf(':')));
        DanhSachDongGopController.setDanhSachChuaDongGop(JpnTable, eventID);  //danh sach chua dong

    }//GEN-LAST:event_JcbEventActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbEvent;
    private javax.swing.JPanel JpnTable;
    // End of variables declaration//GEN-END:variables
}
