/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Payment;

import controllers.DanhSachDongGopController;
import controllers.DongGopPanelController;
import javax.swing.JComboBox;
import services.DongGopService;

/**
 *
 * @author Administrator
 */
public class ListPayment extends javax.swing.JFrame {

    private DongGopPanelController dongGopController;
    private final DongGopService dongGopService = new DongGopService();
    public ListPayment() {
        initComponents();
        this.setTitle("Danh sách đóng góp");
        dongGopController = new DongGopPanelController();
        dongGopController.setDataToComboBox(JcbEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnTable = new javax.swing.JPanel();
        JcbEvent = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbtLammoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JlbTongSoTien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JpnTableLayout = new javax.swing.GroupLayout(JpnTable);
        JpnTable.setLayout(JpnTableLayout);
        JpnTableLayout.setHorizontalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JpnTableLayout.setVerticalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        JcbEvent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JcbEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JcbEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbEventActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chọn sự kiện");

        jbtLammoi.setText("Làm mới");
        jbtLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLammoiActionPerformed(evt);
            }
        });

        jLabel2.setText("Tổng số tiền:");

        JlbTongSoTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JlbTongSoTien.setText("0");

        jLabel3.setText("x1000 đồng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JcbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(JlbTongSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jbtLammoi)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(JcbEvent, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jbtLammoi)
                    .addComponent(jLabel2)
                    .addComponent(JlbTongSoTien)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JpnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbEventActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String eventName = (String)cb.getSelectedItem();
        if(eventName.indexOf(':') <0 ) return;
        int eventID = Integer.parseInt(eventName.substring(0, eventName.indexOf(':')));
        DanhSachDongGopController dsdonggop = new DanhSachDongGopController(JpnTable, eventID);
        JlbTongSoTien.setText(Integer.toString(dongGopService.totalPayment(eventID)));
        
    }//GEN-LAST:event_JcbEventActionPerformed

    private void jbtLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLammoiActionPerformed
       
        String eventName = (String)JcbEvent.getSelectedItem();
        if(eventName.indexOf(':') <0 ) return;
        int eventID = Integer.parseInt(eventName.substring(0, eventName.indexOf(':')));
        DanhSachDongGopController dsdonggop = new DanhSachDongGopController(JpnTable, eventID);
        JlbTongSoTien.setText(Integer.toString(dongGopService.totalPayment(eventID)));
    }//GEN-LAST:event_jbtLammoiActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbEvent;
    private javax.swing.JLabel JlbTongSoTien;
    private javax.swing.JPanel JpnTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtLammoi;
    // End of variables declaration//GEN-END:variables
}
